#!/bin/bash
echo
curl -s ifconfig.co | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" > tmp.tmp
IP=$(cat tmp.tmp)
echo "
Scanning for open ports on $IP...
"
echo
nmap $IP > tmp.tmp
awk 'NR > 4' tmp.tmp > tmp2.tmp
head -n -2 tmp2.tmp > tmp.tmp
cat tmp.tmp
echo "
Done!
"
rm -r *.tmp
